### PR TITLE
cordon limiter

### PR DESCRIPTION
**Pull request by dbenque**
Proposition of implementation for #89 

The new flags are not mandatory. Behavior of `draino` is unchanged if new flag are absent.
The flags for limits can be repeated and cumulated. See README for details.

### CODE REVIEW

**Comment by dbenque** [comment]
@jacobstr FYI, I have used that feature  (build from our fork) on our clusters, and we have been able to rotate several thousands of nodes in a really smooth and controlled way.

**Comment by jacobstr** [comment]
@dbenque pardon the delay looking this over. Had a storm of merges a few weeks ago and haven't given draino the ❤️ since then. This looks like a worthy contribution and I'm happy to give it a look over and mainline it. Ya'll are probably running a lot of draino forks over at DataDog :)

**Comment by dbenque** [comment]
> @dbenque pardon the delay looking this over. Had a storm of merges a few weeks ago and haven't given Draino the ❤️ since then. This looks like a worthy contribution and I'm happy to give it a look over and mainline it. Ya'll are probably running a lot of draino forks over at DataDog :)

@jacobstr, yes we are, I have couple of contributions that I would like to add to `draino`. I think it would make sense that we meet (video-call) to discuss a bit about these possible evolutions to check if they fit in our `draino` roadmap or if I need to think about other ways to achieve some of my goals. If ok, can you ping me on the kubernetes slack @ david.benque ?

**Comment by hikhvar** [comment]
Any updates on this? We want to deploy draino to our clusters as well. However we are missing some sort of safe-guard like this to prevent false mass drainings.

**Pull request closed without merging**
